"""
Mapping of server names to their related/complementary servers.

These are used to cross-link server documentation pages. Each server maps
to a list of other server names that users commonly use alongside it.

Server names must match the server registry name exactly.
"""

SERVER_RELATED: dict[str, list[str]] = {
    "Acuity Scheduling": ["Google Calendar", "Calendly"],
    "AgentMail": ["Gmail", "Mailchimp"],
    "Ahrefs": ["Firecrawl", "Exa"],
    "Apify": ["Firecrawl", "Bright Data", "Simplescraper"],
    "Atlassian": ["Linear", "Github"],
    "BetterStack": ["Datadog", "Sentry", "Posthog"],
    "Bitly": ["Short.io"],
    "Braintrust": ["Datadog", "Posthog"],
    "Bright Data": ["Firecrawl", "Apify", "Simplescraper"],
    "Calendly": ["Google Calendar", "Acuity Scheduling"],
    "Close": ["Salesloft", "Outreach", "LinkedIn Research"],
    "Context7": ["Firecrawl", "Tavily"],
    "Coresignal": ["LinkedIn Research", "Hunter"],
    "Datadog": ["Sentry", "BetterStack", "Posthog"],
    "Dropcontact": ["Hunter", "LinkedIn Research"],
    "Elementary Data": ["Datadog", "Posthog"],
    "ElevenLabs": ["Listentic"],
    "Enigma": ["Exa", "Tavily"],
    "Exa": ["Tavily", "Firecrawl", "Perplexity"],
    "Exa Websets": ["Exa", "Tavily"],
    "Fellow AI": ["Google Calendar", "Slack", "Fireflies", "Granola"],
    "Firecrawl": ["Exa", "Bright Data", "Tavily", "Simplescraper"],
    "Fireflies": ["Fellow AI", "Granola", "Slack"],
    "Fulcra Context": ["Exa", "Tavily"],
    "Github": ["Linear", "Atlassian", "Sentry"],
    "Gmail": ["Google Calendar", "Google Contacts", "Google Drive", "Slack"],
    "Google Apps Script": ["Google Sheets", "Google Docs", "Google Drive"],
    "Google Calendar": ["Gmail", "Google Contacts", "Calendly", "Fellow AI"],
    "Google Chat": ["Gmail", "Slack", "Google Calendar"],
    "Google Contacts": ["Gmail", "Google Calendar", "Hunter"],
    "Google Docs": ["Google Drive", "Google Sheets", "Notion"],
    "Google Drive": ["Google Docs", "Google Sheets", "Notion"],
    "Google Forms": ["Google Sheets", "Google Drive"],
    "Google Sheets": ["Google Drive", "Google Docs", "Google Forms"],
    "Google Slides": ["Google Drive", "Google Docs"],
    "Google Tasks": ["Google Calendar", "Linear", "Notion"],
    "Granola": ["Fellow AI", "Fireflies", "Slack"],
    "Hunter": ["Dropcontact", "LinkedIn Research", "Coresignal"],
    "Intercom": ["Slack", "Gmail"],
    "Klaviyo": ["Mailchimp", "Shopify"],
    "LeadFuze": ["Hunter", "LinkedIn Research", "Dropcontact"],
    "Linear": ["Github", "Slack", "Notion"],
    "LinkedIn": ["LinkedIn Research", "Hunter"],
    "LinkedIn Research": ["LinkedIn", "Hunter", "Coresignal"],
    "Listentic": ["ElevenLabs"],
    "Mailchimp": ["Klaviyo", "Gmail"],
    "Needle": ["Notion", "Google Drive"],
    "Neon": ["Datadog", "Sentry"],
    "Notion": ["Linear", "Google Docs", "Google Drive", "Slack"],
    "Octagon": ["Exa", "Perplexity"],
    "Outreach": ["Salesloft", "Close", "Gmail"],
    "Perplexity": ["Exa", "Tavily", "Firecrawl"],
    "Polar Signals": ["Datadog", "BetterStack"],
    "Posthog": ["Datadog", "BetterStack", "Sentry"],
    "Postman": ["Github"],
    "Public.com": [],
    "QuickBooks": ["Shopify"],
    "Salesloft": ["Outreach", "Close", "Gmail"],
    "Scorecard": [],
    "Sentry": ["Datadog", "BetterStack", "Github"],
    "Shopify": ["Klaviyo", "Mailchimp", "QuickBooks"],
    "Short.io": ["Bitly"],
    "Simplescraper": ["Firecrawl", "Bright Data", "Apify"],
    "Slack": ["Gmail", "Linear", "Github", "Notion"],
    "Tavily": ["Exa", "Firecrawl", "Perplexity"],
    "Twilio": ["Slack", "Gmail"],
    "Webflow": ["Google Sheets", "Shopify"],
}
